### ISSUE TITLE
Build issue on system with limited memory

### ISSUE THREAD

**Issue by DCNick3** [payonel/ocvm#19]
When ran on system with low amount of memory available build does not work, because of hardcoded `-j4` flag in `Makefile` (many g++ processes begin to eat memory, and lunix starts to swap memory very hard, which leads to system hanging or even OOM-killer waking up). I suggest removing `MAKEFLAGS+="-j 4"` line from `Makefile`, or adding some environment variable so this behavior could be disabled without editing `Makefile`.

**Comment by payonel** [comment]
fixed in 41bf80ae1a4c2dd1f9d6ff2500d61ec56cd54c87
