### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by jonatsp** [payonel/ocvm#3]
When trying to compile in linux there is the following error:
```
g++: error: ../lua-5.3.4/src/liblua.a: File or directory not found
make: *** [Makefile:39: ocvm] Error 1
```

**Comment by payonel** [comment]
looks like you tried to build the project using `make lua=5.3` ? While I do plan to allow that make option for building against any arbitrary lua version, for now in my testing the 5.3 version is specifically pointing to a local build of lua that I have (not the path in the error "../lua-5.3.4")

I can leave this ticket open, however, as a reminder to remove this hack I have in the makefile (for my own testing purposes) to remind me to provide a more generic makefile later on.

**Comment by payonel** [comment]
local lua support has been moved to `make lua=local`
now you can build with any custom named lua package, and `make lua=5.3` will use lua5.3
