### ISSUE TITLE
Debugging EEPROM for PC

### ISSUE THREAD

**Issue by rasongame** [payonel/ocvm#30]
Is it possible to make ocvm not close, but display the EEPROM error screen as PC in OpenComputers?

**Comment by bauen1** [comment]
You could probably achieve something like this by editing `machine.lua` provided by OC to display the error instead of "re-throwing" it.
(currently the eeprom error just ends up in the log)

**Comment by payonel** [comment]
actually, i've been thinking abuot this too! - yeah, i'll make this happen

**Comment by payonel** [comment]
instead of OC's natural looking bluescreen, i decided to just have the vm print to stdout its crash message (after the tty has been reset for normal use). I think everyone will like this much more

**Comment by rasongame** [comment]
nice fix :) thx
