### ISSUE TITLE
Error when launching ocvm

### ISSUE THREAD

**Issue by LegoLivesMatter** [payonel/ocvm#32]
I successfully built ocvm and started it, but it only cleared the terminal and exited out. When running it with `--frame=basic` it says:

`failed to initialize: filesystem`

I already tried installing `luafilesystem` with luarocks, but it didn't help.

**Comment by payonel** [comment]
check the `log` in case there are more details than what --frame=basic prints out
(e.g. `tmp/log`)

i bet your `make` didn't download the system dir it needs
do you have `wget` and `svn` on your system? you don't have to have svn, you just need to properly popualte the `system/` directory. ocvm points to system/ things for machine.lua, bios, and the boot floppy (default openos)

**Comment by LegoLivesMatter** [comment]
OpenOS was missing, which was weird because I have svn and wget on my system. Thanks for reminding me.
