### ISSUE TITLE
Can't compile for arm

### ISSUE THREAD

**Issue by ewwhash** [payonel/ocvm#39]
I trying to compile OCVM using termux and clang, but it failed.

uname -a 
Linux localhost 3.18.14-14961013-QB26445291 #1 SMP PREEMPT Mon Oct 7 20:55:19 KST 2019 armv8l Android

error https://pastebin.com/raw/bMVFXeLV

**Comment by payonel** [comment]
can i get a full clang version print? is this raspberry pi with arm?

**Comment by payonel** [comment]
closed by 9aa280a61482cdabbf0e2f8128962a627059f5f2
