### ISSUE TITLE
doesnt run on arch linux

### ISSUE THREAD

**Issue by z3roco01** [payonel/ocvm#49]
im on arch linux i compiled it and when i run it it just clears the terminal

**Comment by Ocawesome101** [comment]
do you have the `system/machine.lua`, `system/font.hex`, and `system/loot` folders in the OCVM folder?  they are required for the emulator to work.

**Comment by z3roco01** [comment]
i didnt but now i do and it works

**Comment by Ocawesome101** [comment]
Good.  Close this issue then since it’s resolved.
